server:
  port: 8000
  servlet:
    context-path: /
#  ssl:
#    key-store: C:/Program Files/Java/jdk-15.0.1/bin/keystore_test.p12
#    key-store-type: PKCS12
#    key-alias: key_test
#    key-store-password: 123456

spring:     
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itsminedb2?serverTimezone=Asia/Seoul
    username: dong1
    password: gml7439416
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true